version: '3'
services:
  # Frontend Service
  frontend:
    build:
      context: ./Techdome-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # Backend Service
  backend:
    build:
      context: ./Techdome-backend
    ports:
      - "8050:8050"
    environment:
      MONGO_URI: "mongodb+srv://Anand:Anand123@cluster0.a5kwk.mongodb.net/blog?retryWrites=true&w=majority"

